# Generated by Django 3.1.2 on 2020-10-18 12:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 10, 18, 12, 27, 36, 547247, tzinfo=utc))),
            ],
        ),
    ]
