# Generated by Django 3.1.2 on 2020-10-18 15:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('makkal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='securty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 18, 15, 22, 39, 729581, tzinfo=utc)),
        ),
    ]
