# Generated by Django 3.1.2 on 2020-10-19 04:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('makkal', '0002_auto_20201018_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='securty',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 4, 22, 31, 401282, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 4, 22, 31, 400313, tzinfo=utc)),
        ),
    ]
