# Generated by Django 3.1.2 on 2020-10-19 04:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('makkal', '0003_auto_20201019_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.AlterField(
            model_name='securty',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 4, 25, 19, 939940, tzinfo=utc)),
        ),
    ]
