# Generated by Django 3.1.2 on 2020-10-19 04:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('makkal', '0004_auto_20201019_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securty',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 4, 29, 19, 198568, tzinfo=utc)),
        ),
    ]
