# Generated by Django 3.1.2 on 2020-10-19 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makkal', '0005_auto_20201019_0429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securty',
            name='date',
        ),
    ]
